name: Deploy

on:
  push:
    branches: master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # 把 node.js 版本記錄在這，之後可以重新取出作為 cache key

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@master

      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: 💾 Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
        # cache key 包含了所有我們希望固定的資訊：OS，node 版本，以及 package-lock.json 的檔案內容，使用 hashFiles 將檔案內容轉換成字串
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: 🔨 Build Project
        run: |
          test -d node_modules && echo "node_modules exists" || npm ci
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.willytylee.com
          username: willytylee
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: /domains/eta.willytylee.com/
